#!/usr/bin/env bash
#bash that transfer file to a remote server

if [ "$#" -lt 4 ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    exit 1
else
    PATH_TO_FILE=$1
    IP_OF_SERVER=$2
    REMOTE_USER=$3
    PATH_TO_SSH_KEY=$4
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$REMOTE_USER@$IP_OF_SERVER:"
fi
