#!/bin/bash

#installing nginx

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

sed -i 's/80 default_server/80 default_server;/' /etc/nginx/sites-available/default

service nginx restart
