#!/usr/bin/env bash
#Redirecting a traffic to an alternative websit

sudo apt-get -y update
sudo apt-get -y install nginx

replaceText="rewrite ^/redirect_me https://github.com/enejivk permanent;"
sed -i "s|server_name _;|$replaceText|g" /etc/nginx/sites-available/default

sudo service nginx start