#!/usr/bin/env bash
#Redirecting a traffic to an alternative websit

sudo apt-get -y update
sudo apt-get -y install nginx

replaceText="rewrite ^/redirect_me https://github.com/enejivk permanent;"
sed -i "s|server_name _;|$replaceText|&\n\tg" /etc/nginx/sites-available/default


echo "Ceci n'est pas une page" > /var/www/html/404.html
errorPage="error_page 404 404.html;\n\tlocation = /404.html;\n\t\troot /var/www/html;\n\t\tinternal;"
sed -i "s|server_name _;|&\n\t\$errorPage|g" /etc/nginx/sites-available/default


header="add_header X-Served-By '515457-web-02';"
sed -i "s|server_name _;|&\n\t$header|g" /etc/nginx/sites-available/default

sudo service nginx start