#!/usr/bin/env bash
#printing of numbers from one to 20
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

number_of_times=0
while [ $number_of_times -lt 20 ]
do
    ((number_of_times++))
    echo "$number_of_times"
    case $number_of_times in
    4 )
        echo "bad luck from China";;
    9 )
        echo "bad luck from Japan";;
    17 )
        echo "bad luck from Italy";;
    * )
esac
done
