#!/usr/bin/env bash
#printing of numbers from one to 20
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

number_of_times=1
while [ $number_of_times -lt 21 ]
do
    echo "$number_of_times"
    if [ $number_of_times -eq 4 ]
        then
            echo "bad luck from China"
        fi

    if [ $number_of_times -eq 9 ]
        then
            echo "bad luck from Japan"
        fi
        
    if [ $number_of_times -eq 17 ]
        then
            echo "bad luck from Italy"
        fi

    ((number_of_times++))
done
