#!/usr/bin/env bash
#printing of clock

hour=0
while [ $hour -le 12 ]
     do
    echo "Hour: $hour"
    
    minute=1
    while [ $minute -lt 59 ]
     do
        echo "$minute"
        ((minute++))
    done

    ((hour++))
done
